Realm Kotlin SDK
mohit-sharma-87/DevHub-Articles pull request #3
Opened 2022-03-03 07:41 UTC by mohit-sharma-87

2022-03-03 11:06 UTC, cmelchior requested changes
Hi @mohit-sharma-87 

I added some comments to the doc. Sorry to be annoying, but this article does feel a bit rushed. A lot of sentences could need a proofreader and the content seems to mix both Sync and Local database changes (and Sync is still Alpha) + the half the content is on setting up Gradle rather than focusing on the interesting changes in the API like coroutine support + the new query and notification system

I know there might not be time to incorporate all of this feedback, but I would probably suggest that we repurpose this article for the Sync Beta instead and not try to rush it out.

2022-03-03 11:06 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +Upon quick comparing, you would notice that lines of code have decreased by 30%, and we are using
This example is a mixing login with notifications which feels as bit wrong...Maybe just focus on the notifications, which has gotten quite an upgrade using sealed classes.

2022-03-03 11:06 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +## Other major changes
This is super relevant ...I would move this section to the top.

2022-03-03 12:04 UTC, mohit-sharma-87 commented
> Hi @mohit-sharma-87
> 
> I added some comments to the doc. Sorry to be annoying, but this article does feel a bit rushed. A lot of sentences could need a proofreader and the content seems to mix both Sync and Local database changes (and Sync is still Alpha) + the half the content is on setting up Gradle rather than focusing on the interesting changes in the API like coroutine support + the new query and notification system
> 
> I know there might not be time to incorporate all of this feedback, but I would probably suggest that we repurpose this article for the Sync Beta instead and not try to rush it out.

Thanks for your valuable feedback and I will try to incorporate the changes suggested.

2022-03-03 12:22 UTC, mohit-sharma-87 commented on Migration to Realm Kotlin SDK.md
> +3. Setup logging
Just highlighting that logging is now part of config builder.

2022-03-03 12:26 UTC, mohit-sharma-87 commented on Migration to Realm Kotlin SDK.md
> +1. <s>Call `Realm.init()`</s> _Is not needed anymore_.
Got it, updated copy

2022-03-03 12:31 UTC, mohit-sharma-87 commented on Migration to Realm Kotlin SDK.md
> +        val realm = Realm.open(configuration = config)
Can in this case but not where `partitionValue` keeps changing based on the behaviour of screen. Therefore keeping it as it is to avoid confusion.

2022-03-03 12:42 UTC, mohit-sharma-87 commented on Migration to Realm Kotlin SDK.md
> +With this, our Android app is ready to use the new Realm Kotlin SDK.
@cmelchior : This is done purpose based on my experience and trouble setting up SDK due to changes in the Android build process. 

"Also you mention Sync under Java SDK but not under Kotlin...I would probably just remove references to it, since it is just confusing right now." - From the user's point of view it's just one SDK for Realm (Local + Sync), so I am referring to old SDK as Java SDK in general.

2022-03-04 13:46 UTC, cmelchior requested changes
I still have some reservations about this blog post.

A lot of the comparisons are not doing the same thing, which makes it a bit unfair to compare. Also, the Realm being managed in the ViewModel is kinda promoting the wrong pattern (at least without more context).

And I'm still not sure why we want Sync involved here...We can easily show reduction in boilerplate without using Sync.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +Multiplatform.
As a minimum, we should make it really clear that Sync is still alpha, because just reading this you get the impression it is also in Beta.

But I still feel trying to focus on Sync is a bad idea. It distracts from the API changes  which works just when using either sync or the local database.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +}
Bracers are not aligned correctly in this section

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +}
Bracers are not aligned correctly in this section

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +4. Configure Realm Sync, if needed.
Not sure what is being referred to here?

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +4. **Add a list of Realm classes(/models) to `RealmConfiguration` builder as a part of `schema`.**
This is actually subsections of 2) where as in the Java SDK it was different API's.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +Apart from this, few data types like `@RealmClass`,`ByteArray`,`RealmDictionary`,`RealmSet`,
`@RealmClass` is not a data type, but an annotation. If we want to mention those then `@RealmField` is not supported either.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +Kotlin Flow, etc. was not available.
This is not true, we have support for coroutines in Java. The biggest problems were the build system: Annotation processors are slow and didn't provide full insight into the Kotlin type system.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +        val realm = Realm.open(configuration = config)
Fair enough, but like I mentioned, it would be better if the Realm lifecycle was handled better. Either by closing the Realm here or by using:

```
class MyScreen : ViewModel() {
  private lateinit var: realm: Realm
  fun updateData() {

  }
  override fun onCleared() {
      super()
      realm.close()
  }
}
```

Otherwise Realm instances are going to leak here.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +        val realm = Realm.open(configuration = config)
Also, this is a bit unfaithfull, as you would need a try catch around this to have the same error handling as in the Java sample

```
try {
 // Open Realm
} catch (ex: Exception) {
  // Handle error
} 
```

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +    return realm.query<VisitInfo>().first().asFlow()
These two examples does not do the same.

In Java you do a one-off query that update the UI once, while in Kotlin you expose a Flow. The Java also controls a isLoading state, which the Kotlin sample does not.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +than **60%**. What led to such a drastic change?
This is not a fair comparison...the Java sample does more things than the Kotlin one.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +    val user = realmApp.login(Credentials.anonymous())
Again, this is "cheating" a bit...you would need a try/catch around this to have similar functionality.

2022-03-04 13:46 UTC, cmelchior commented on Migration to Realm Kotlin SDK.md
> +            copyToRealm(visitInfo?.updateCount()
You don't need to `copyToRealm` the managed object, which this code will do, updating it directly should work fine.

```
if (visitInfo == null) {
   copyToRealm(...)
} else {
  visitInfo.updateCount();
}
```

2022-03-13 14:11 UTC, closed without merging