Getting started with KMM
mohit-sharma-87/DevHub-Articles pull request #4
Opened 2023-01-10 09:38 UTC by mohit-sharma-87

https://github.com/mohit-sharma-87/DevHub-Articles/blob/get_started_kmm/Getting%20Started%20with%20KMM.md

2023-01-10 23:05 UTC, DominicFrei requested changes
Nice one, @mohit-sharma-87 ! 💪 

I didn't see anything major but left some comments. Hope they help. :)

2023-01-10 23:05 UTC, DominicFrei commented on Getting Started with KMM.md
> +no additional implementation is required to make it realtime.
```suggestion
With this done our application is ready to send and receive data in real-time. Yes, in real-time. No additional implementation is required to make it real-time.
```

To be absolutely precise, it's not real-time, but it's freakingly fast. :)

2023-01-10 23:05 UTC, DominicFrei commented on Getting Started with KMM.md
> +Also, you view or modify the data received via `saveInfo` function using `Atlas` UI.
```suggestion
Also, you can view or modify the data received via the `saveInfo` function using the `Atlas` UI.
```

2023-01-10 23:05 UTC, DominicFrei commented on Getting Started with KMM.md
> +![Atlas UI](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/Screenshot_2023_01_10_at_09_17_27_2a1a38dece.png)
I just noticed it here but it also targets all other screenshots.
I'd leave an empty line before the screenshot in your markdown. That way the text above it does not stick to the screenshot directly. Unless you want that. :)

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +etc). Some common use cases for shared code are getting data from the network, saving it into the
removed etc.

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +than complete code which often makes things complicated.
Done, added a line here.

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +This is only basic we need before building a complex and full-fledged real app.
Done

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +    suspend fun saveInfo(query: String) {
No, suspend is an integration part of the Kotlin language.

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +   ```kotlin
Fixed it

2023-01-11 10:39 UTC, mohit-sharma-87 commented on Getting Started with KMM.md
> +4. Enable Atlas Device Sync using Flexible Sync, as shown below
Added some additional text..

2023-02-01 11:30 UTC, merged