Create SpringBoot-Kotlin-MongoDB.md
mohit-sharma-87/DevHub-Articles pull request #5
Opened 2023-02-01 11:36 UTC by mohit-sharma-87

2023-02-02 11:56 UTC, dfreniche requested changes
A few suggestions/changes

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +the name of the project, language, version of `Spring Boot`, etc to something similar as shown
This part is not accessible. We sould:
1. add a bullet point list of the settings, as not everybody can see that image
2. add a meaningful alt description to that image. In this case, it can be that bullet list
To add alt description to an image in MD use
```
![Alt text goes here](/path/to/img.jpg “image title appears under image”)
```

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +![Spring Initialier](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/Spring_initializr_dbbfd7e79a.png)
Typo: initializer

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +
OK, this is explained below, but not sure if at least we should introduce it at least as a "popular framework to build web apps"

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +   Routing is nothing but a mapping of `Http` request path (text after `host/`) to classes that
Http -> HTTP as it's an acronym

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +For our app, we would be using MongoDB as a database which is a document database. It's an
we would -> we will
This is not a possibility 😂

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +I would recommend you explore, the
recommend you explore -> recommend you to explore

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +With the basics for MongoDB covered, now let's connect our SpringBoot project with it. Connect
Connecting to MongoDB...

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +found as shown below.
Here we can also add this doc: https://www.mongodb.com/docs/guides/atlas/connection-string/

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +## Creating CRUD Restful app
Creating "a" CRUD Restful app

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +we would be covering all CRUD operations and tweaking them along the way to make it a more realistic
we would be covering -> will

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +You can load a sample dataset on Atlas as shown below
We also have a step by step: https://www.mongodb.com/developer/products/atlas/atlas-sample-datasets/

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +`@Document` declares that this data class represent a document in the Atlas.
put these two in a bullet-point list?

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +class Controller(@Autowired val repo: Repo) {
Can you explain what `@Autowired` is?

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +Taking a step further to read restaurant based `restaurantId`, we would have to add a method in
we would have -> we will have

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +
Missing here a line explaining that you're going to test it using Postman?

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +Let's also validate this against an invalidate `restaurantId` as well.
this against an invalidate -> this against a non-valid

I think invalidate is a verb

2023-02-02 11:56 UTC, dfreniche commented on SpringBoot-Kotlin-MongoDB.md
> +be improved further if we used [MongoDB native driver](https://www.mongodb.com/docs/drivers/) which
if we used -> if we use the

2023-02-02 17:45 UTC, DominicFrei reviewed
@mohit-sharma-87 Only had some smaller additions to @dfreniche . Overall it looks good to me. :)

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +![Hello World Output](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/Hello_World_output_279aed0e43.png)
![image](https://user-images.githubusercontent.com/1942012/216394577-27f683bf-350b-48fa-865c-8a2983c9c61d.png)

This is how that screenshot looks to me. It looks like something's broken. I'd crop it or make sure the background color is slightly different from the GitHub background color.

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +And on cross-validating this from [Postman](https://www.postman.com) we can clearly understand
Your could create a public request on Postman and link it so that users can use it directly.

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +[As per official docs](https://spring.io/projects/spring-boot#overview) - _Spring Boot makes it
> I'd use the same quote mechanism you used in the beginning of the article.

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +with MongoDB is really simple thanks to the Spring Data MongoDB plugin.
Link?

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +![DB URL](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/find_Connect_Stream_URL_e7a6c2257a.gif)
Do all platforms you publish on support gif?

2023-02-02 17:45 UTC, DominicFrei commented on SpringBoot-Kotlin-MongoDB.md
> +## Creating CRUD Restful app
```suggestion
## Creating CRUD RESTful app
```

2023-02-03 17:51 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +> SpringBoot 3 and MongoDB.
Done & MongoDB Atlas

2023-02-03 17:51 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +So today, we are going build a basic application that does a little more than a CRUD operation while
Done

2023-02-03 18:05 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +which has the `main` function as well.
I will ignore this, as the code is generated by the spring app.

2023-02-03 18:39 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +![DB URL](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/find_Connect_Stream_URL_e7a6c2257a.gif)
Yes!

2023-02-03 18:42 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +```
Did it on purpose to avoid IDE error

2023-02-03 18:58 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +
Done

2023-02-07 05:21 UTC, mohit-sharma-87 reviewed
PR comments

2023-02-07 06:05 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +
Done

2023-02-07 06:19 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +with MongoDB is really simple thanks to the Spring Data MongoDB plugin.
Plugins don't have a link, except for the gradle repo link which doesn't make sense in this context.

2023-02-07 06:21 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +![model](https://mongodb-devhub-cms.s3.us-west-1.amazonaws.com/Read_72aa6d89de.png)
Looks good in the actual copy, I will validate it with Megan as well.

2023-02-07 16:11 UTC, erikhatcher reviewed
I enjoyed this article, @mohit-sharma-87!   I made a few minor suggestions in comments here, otherwise looks good to me!

2023-02-07 16:11 UTC, erikhatcher commented on SpringBoot-Kotlin-MongoDB.md
> +And since, we want to create REST API with MongoDB as a database let's add the dependency using Add
create _a_ REST API?    Or... to create REST API_s_??

2023-02-07 16:11 UTC, erikhatcher commented on SpringBoot-Kotlin-MongoDB.md
> +   it's a Spring Boot project and allows enabling feature which can also be done using
enabling feature_s_

2023-02-07 16:11 UTC, erikhatcher commented on SpringBoot-Kotlin-MongoDB.md
> +    val restaurant = Restaurant().copy(name = "sample", restaurantId = "33332")
I'm confused on this line of code.   Is this just going to add the same restaurantId over and over?   I'm missing how the post parameters would make it to a new Restaurant object

2023-02-07 16:11 UTC, erikhatcher commented on SpringBoot-Kotlin-MongoDB.md
> +Thank you for reading and hopefully find this article informative! The Complete source code of the
...and hopefully _you_ find this article...

2023-02-07 16:11 UTC, erikhatcher commented on SpringBoot-Kotlin-MongoDB.md
> +operation and for that we would use
...we _will_ use...

2023-02-07 21:42 UTC, mohit-sharma-87 commented on SpringBoot-Kotlin-MongoDB.md
> +    val restaurant = Restaurant().copy(name = "sample", restaurantId = "33332")
Added new method with Request Params to clear this confusion.

2023-02-07 21:43 UTC, merged